// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcdtET_89sjGAPJhjktqmtSwxOWFctOYM',
    appId: '1:309490598651:web:080f058df0fe98d11ea65e',
    messagingSenderId: '309490598651',
    projectId: 'secondchance-8444f',
    authDomain: 'secondchance-8444f.firebaseapp.com',
    storageBucket: 'secondchance-8444f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoEb_bmjz-3fs_m7wItBU_dRUpG6EXLvc',
    appId: '1:309490598651:android:6678b38be17e5b871ea65e',
    messagingSenderId: '309490598651',
    projectId: 'secondchance-8444f',
    storageBucket: 'secondchance-8444f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUxI4EEYYwz39F_zEavC2vp05sGDL8RPU',
    appId: '1:309490598651:ios:cd071ce90de3d4de1ea65e',
    messagingSenderId: '309490598651',
    projectId: 'secondchance-8444f',
    storageBucket: 'secondchance-8444f.firebasestorage.app',
    iosBundleId: 'com.example.secondChance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUxI4EEYYwz39F_zEavC2vp05sGDL8RPU',
    appId: '1:309490598651:ios:cd071ce90de3d4de1ea65e',
    messagingSenderId: '309490598651',
    projectId: 'secondchance-8444f',
    storageBucket: 'secondchance-8444f.firebasestorage.app',
    iosBundleId: 'com.example.secondChance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcdtET_89sjGAPJhjktqmtSwxOWFctOYM',
    appId: '1:309490598651:web:276c170b43fd297c1ea65e',
    messagingSenderId: '309490598651',
    projectId: 'secondchance-8444f',
    authDomain: 'secondchance-8444f.firebaseapp.com',
    storageBucket: 'secondchance-8444f.firebasestorage.app',
  );

}